import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import LabelEncoder
import joblib
from pathlib import Path

# Load the descriptor CSV generated by shape_classification_resize.py.
SCRIPT_DIR = Path(__file__).resolve().parent
CSV_PATH = SCRIPT_DIR / "shape_descriptors_project_640x480.csv"
MODEL_PATH = SCRIPT_DIR.parent / "shape_descriptor" / "decision_tree_model_final.joblib"

df = pd.read_csv(CSV_PATH)


# REQUIRED DESCRIPTORS (MUST MATCH CLASSIFICATION)

FEATURE_COLUMNS = [
    "Area",
    "Perimeter",
    "Circularity",
    "Compactness",
    "Convexity"
]

TARGET_COLUMN = "Label"


# Sanity check (prevents silent bugs)

missing = set(FEATURE_COLUMNS + [TARGET_COLUMN]) - set(df.columns)
if missing:
    raise ValueError(f"Missing required columns in CSV: {missing}")


# Select features and labels explicitly

X = df[FEATURE_COLUMNS].copy()
y = df[TARGET_COLUMN].copy()


# Encode string labels → integers

label_encoder = LabelEncoder()
y_encoded = label_encoder.fit_transform(y)


# Train decision tree

clf = DecisionTreeClassifier(
    criterion="gini",
    max_depth=None,
    random_state=42
)
clf.fit(X, y_encoded)


# Save model bundle (TRAINING ↔ INFERENCE MATCH)

joblib.dump(
    {
        "decision_tree": clf,
        "label_encoder": label_encoder,
        "feature_names": FEATURE_COLUMNS
    },
    MODEL_PATH
)

print(f"Model trained and saved successfully: {MODEL_PATH}")
print("Feature order:", FEATURE_COLUMNS)
print("Classes:", label_encoder.classes_)
